runtime: nodejs20
env: standard

# Use this to connect to your Google Cloud SQL instance
beta_settings:
  cloud_sql_instances: loqation-experience-demo:europe-west10:trade-fair-demo

env_variables:
  NODE_ENV: "production"
  DB_HOST: "34.32.119.210"
  INSTANCE_CONNECTION_NAME: "loqation-experience-demo:europe-west10:trade-fair-demo"
  DB_USER: "root"
  DB_PASSWORD: "#XVEL0|k%{[0Nyc5"
  DB_NAME: "loqations-trade-fair"
  GOOGLE_CLIENT_ID: "621124414399-57v1o3ba343v1dcabd63d029053dphl9.apps.googleusercontent.com"
  JWT_SECRET: "ahafkhgkasaygjhgajksfashflashlakshfiauf"